apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: note
  name: note
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: note
    spec:
      containers:
      - image: vasugoriya/my-note-app
        name: my-note-app

